CFLAGS_FALLTHROUGH="-Wimplicit-fallthrough=0"
CFLAGS="${CFLAGS} ${CFLAGS_FALLTHROUGH}"
CXXFLAGS="${CXXFLAGS} ${CFLAGS_FALLTHROUGH}"
FCFLAGS="${FCFLAGS} ${CFLAGS_FALLTHROUGH}"
FFLAGS="${FFLAGS} ${CFLAGS_FALLTHROUGH}"
