CFLAGS="${CFLAGS_COMMON} ${CFLAGS_COMPILER} ${CFLAGS_CPU} ${CFLAGS_SSP} ${CFLAGS_FORTIFY} ${CFLAGS_PIE}"
CXXFLAGS="${CFLAGS}"
FCFLAGS="${CFLAGS}"
FFLAGS="${CFLAGS}"

LDFLAGS="${LDFLAGS_COMMON} ${LDFLAGS_PIE}"
