CFLAGS_CPU="-march=haswell -mmmx -msse -msse2 -msse3 -mssse3 -msse4 -mavx -maes -mfpmath=sse"
CFLAGS="${CFLAGS_COMMON} ${CFLAGS_COMPILER} ${CFLAGS_CPU} ${CFLAGS_SSP} ${CFLAGS_FORTIFY}"
CXXFLAGS="${CFLAGS}"
FCFLAGS="${CFLAGS}"
FFLAGS="${CFLAGS}"

LDFLAGS="${LDFLAGS_COMMON}"

CPU_FLAGS_X86="aes avx mmx mmxext pclmul popcnt sse sse2 sse3 ssse3"
