PORTAGE_USERNAME=root
PORTAGE_GRPNAME=root

FEATURES_SELINUX="-selinux -sesandbox"
FEATURES_SANDBOX="-sandbox -usersandbox -network-sandbox"
FEATURES_USERPRIV="-userfetch -userpriv -usersync"
FEATURES="${FEATURES} ${FEATURES_SELINUX} ${FEATURES_SANDBOX} ${FEATURES_USERPRIV}"
