BINPKG_GPG_SIGNING_GPG_HOME='/etc/portage/gnupg/releng/gnupg'
BINPKG_GPG_SIGNING_KEY='0xF5C62A27BE1D3DAEC417CF79CE48952C411666D9'
BINPKG_GPG_SIGNING_BASE_COMMAND="/usr/bin/flock /run/portage-binpkg-gpg.lock /usr/bin/gpg --sign --armor [PORTAGE_CONFIG]"
PORTAGE_TRUST_HELPER=""

FEATURES="${FEATURES_BINPKG_SIGNING}"
