# -fno-lto

EN_LDFLAGS_COMPILER_LTO="${EN_LDFLAGS_COMPILER_LTO_NO}"
EN_LDFLAGS_COMPILER="${EN_LDFLAGS_COMPILER} ${EN_LDFLAGS_COMPILER_LTO}"

LDFLAGS="${EN_LDFLAGS_COMMON} ${EN_LDFLAGS_COMPILER} ${EN_LDFLAGS_CPU} ${EN_LDFLAGS_DEBUG} ${EN_LDFLAGS_HARDENED} ${EN_LDFLAGS_LINK}"
