# -lpthread

EN_CFLAGS_LINK_LIBS_COMMON="${EN_CFLAGS_LINK_LIBS_COMMON} ${EN_CFLAGS_LINK_LIBS_COMMON_PTHREAD}"

EN_CFLAGS_LINK="${EN_CFLAGS_LINK} ${EN_CFLAGS_LINK_LIBS_COMMON_PTHREAD}"

COMMON_FLAGS="${EN_CFLAGS_COMMON} ${EN_CFLAGS_COMPILER} ${EN_CFLAGS_CPU} ${EN_CFLAGS_DEBUG} ${EN_CFLAGS_HARDENED} ${EN_CFLAGS_LINK}"
CFLAGS="${EN_CFLAGS_COMMON} ${EN_CFLAGS_COMPILER} ${EN_CFLAGS_CPU} ${EN_CFLAGS_DEBUG} ${EN_CFLAGS_HARDENED} ${EN_CFLAGS_LINK}"
CXXFLAGS="${CFLAGS}"
FCFLAGS="${CFLAGS}"
FFLAGS="${CFLAGS}"
