# -nostdlib

EN_CFLAGS_LINK_LIBS_STD="${EN_CFLAGS_LINK_LIBS_STD} ${EN_CFLAGS_LINK_LIBS_STD_NOSTDLIB}"
EN_CFLAGS_LINK="${EN_CFLAGS_LINK} ${EN_CFLAGS_LINK_LIBS_STD_NOSTDLIB}"

EN_LDFLAGS_LINK_LIBS_STD="${EN_LDFLAGS_LINK_LIBS_STD} ${EN_LDFLAGS_LINK_LIBS_STD_NOSTDLIB}"
EN_LDFLAGS_LINK="${EN_LDFLAGS_LINK} ${EN_LDFLAGS_LINK_LIBS_STD_NOSTDLIB}"

COMMON_FLAGS="${EN_CFLAGS_COMMON} ${EN_CFLAGS_COMPILER} ${EN_CFLAGS_CPU} ${EN_CFLAGS_DEBUG} ${EN_CFLAGS_HARDENED} ${EN_CFLAGS_LINK}"
CFLAGS="${EN_CFLAGS_COMMON} ${EN_CFLAGS_COMPILER} ${EN_CFLAGS_CPU} ${EN_CFLAGS_DEBUG} ${EN_CFLAGS_HARDENED} ${EN_CFLAGS_LINK}"
CXXFLAGS="${CFLAGS}"
FCFLAGS="${CFLAGS}"
FFLAGS="${CFLAGS}"

LDFLAGS="${EN_LDFLAGS_COMMON} ${EN_LDFLAGS_COMPILER} ${EN_LDFLAGS_CPU} ${EN_LDFLAGS_DEBUG} ${EN_LDFLAGS_HARDENED} ${EN_LDFLAGS_LINK}"
