# -Wno-error=builtin-declaration-mismatch

EN_CFLAGS_DIAGNOSTICS_W_NO="${EN_CFLAGS_DIAGNOSTICS_W_NO} ${EN_CFLAGS_DIAGNOSTICS_W_NO_ERROR_BUILTIN_DECLARATION_MISMATCH}"

EN_CFLAGS_DIAGNOSTICS="${EN_CFLAGS_DIAGNOSTICS_W} ${EN_CFLAGS_DIAGNOSTICS_W_NO}"

COMMON_FLAGS="${EN_CFLAGS_COMMON} ${EN_CFLAGS_COMPILER} ${EN_CFLAGS_CPU} ${EN_CFLAGS_DEBUG} ${EN_CFLAGS_DIAGNOSTICS} ${EN_CFLAGS_HARDENED} ${EN_CFLAGS_LINK}"
CFLAGS="${EN_CFLAGS_COMMON} ${EN_CFLAGS_COMPILER} ${EN_CFLAGS_CPU} ${EN_CFLAGS_DEBUG} ${EN_CFLAGS_DIAGNOSTICS} ${EN_CFLAGS_HARDENED} ${EN_CFLAGS_LINK}"
CXXFLAGS="${CFLAGS}"
FCFLAGS="${CFLAGS}"
FFLAGS="${CFLAGS}"
