# No pipe

EN_CFLAGS_COMMON_OPTS=""

EN_CFLAGS_COMMON="${EN_CFLAGS_COMMON_ARCH_ABI} ${EN_CFLAGS_COMMON_ARCH_CPU} ${EN_CFLAGS_COMMON_ARCH_MCMODEL} ${EN_CFLAGS_COMMON_OPTS}"

COMMON_FLAGS="${EN_CFLAGS_COMMON} ${EN_CFLAGS_COMPILER} ${EN_CFLAGS_CPU} ${EN_CFLAGS_DEBUG} ${EN_CFLAGS_DIAGNOSTICS} ${EN_CFLAGS_HARDENED} ${EN_CFLAGS_LINK}"
CFLAGS="${EN_CFLAGS_COMMON} ${EN_CFLAGS_COMPILER} ${EN_CFLAGS_CPU} ${EN_CFLAGS_DEBUG} ${EN_CFLAGS_DIAGNOSTICS} ${EN_CFLAGS_HARDENED} ${EN_CFLAGS_LINK}"
CXXFLAGS="${CFLAGS}"
FCFLAGS="${CFLAGS}"
FFLAGS="${CFLAGS}"

LDFLAGS="${EN_LDFLAGS_COMMON} ${EN_LDFLAGS_COMPILER} ${EN_LDFLAGS_CPU} ${EN_LDFLAGS_DEBUG} ${EN_LDFLAGS_HARDENED} ${EN_LDFLAGS_LINK}"
