# -rtlib=compiler-rt

EN_CC_LINK_LIBS_RT="${EN_CC_LINK_LIBS_RT} ${EN_CC_LINK_LIBS_RT_COMPILER_RT}"

EN_CC_LINK="${EN_CC_LINK} ${EN_CC_LINK_LIBS_RT_COMPILER_RT}"

EN_CC="${CC} ${EN_CC_LINK}"

CC="${EN_CC}"

COMMON_FLAGS="${EN_CFLAGS_COMMON} ${EN_CFLAGS_COMPILER} ${EN_CFLAGS_CPU} ${EN_CFLAGS_DEBUG} ${EN_CFLAGS_HARDENED} ${EN_CFLAGS_LINK}"
CFLAGS="${EN_CFLAGS_COMMON} ${EN_CFLAGS_COMPILER} ${EN_CFLAGS_CPU} ${EN_CFLAGS_DEBUG} ${EN_CFLAGS_HARDENED} ${EN_CFLAGS_LINK}"
CXXFLAGS="${CFLAGS}"
FCFLAGS="${CFLAGS}"
FFLAGS="${CFLAGS}"
