# -stdlib=libc++

EN_CFLAGS_LINK_LIBS_STD="${EN_CFLAGS_LINK_LIBS_STD} ${EN_CFLAGS_LINK_LIBS_STD_LIBCXX}"

EN_CFLAGS_LINK="${EN_CFLAGS_LINK} ${EN_CFLAGS_LINK_LIBS_STD_LIBCXX}"

COMMON_FLAGS="${EN_CFLAGS_COMMON} ${EN_CFLAGS_COMPILER} ${EN_CFLAGS_CPU} ${EN_CFLAGS_DEBUG} ${EN_CFLAGS_HARDENED} ${EN_CFLAGS_LINK}"
CFLAGS="${EN_CFLAGS_COMMON} ${EN_CFLAGS_COMPILER} ${EN_CFLAGS_CPU} ${EN_CFLAGS_DEBUG} ${EN_CFLAGS_HARDENED} ${EN_CFLAGS_LINK}"
CXXFLAGS="${CFLAGS}"
FCFLAGS="${CFLAGS}"
FFLAGS="${CFLAGS}"
