# Undefined version

EN_LDFLAGS_DEBUG_SYMBOLS="${EN_LDFLAGS_DEBUG_SYMBOLS} ${EN_LDFLAGS_DEBUG_SYMBOLS_UNDEFINED_VERSION}"

EN_LDFLAGS_DEBUG="${EN_LDFLAGS_DEBUG_SYMBOLS} ${EN_LDFLAGS_DEBUG_SYMBOLS_UNDEFINED_VERSION}"

LDFLAGS="${EN_LDFLAGS_COMMON} ${EN_LDFLAGS_COMPILER} ${EN_LDFLAGS_CPU} ${EN_LDFLAGS_DEBUG} ${EN_LDFLAGS_HARDENED} ${EN_LDFLAGS_LINK}"
