# no mcx16

EN_CFLAGS_COMPILER_CAS_X86=""

EN_CFLAGS_COMPILER_CAS=""

EN_CFLAGS_COMPILER="${EN_CFLAGS_COMPILER_CAS} ${EN_CFLAGS_COMPILER_FPU} ${EN_CFLAGS_COMPILER_OPTS}"

COMMON_FLAGS="${EN_CFLAGS_COMMON} ${EN_CFLAGS_COMPILER} ${EN_CFLAGS_CPU} ${EN_CFLAGS_DEBUG} ${EN_CFLAGS_HARDENED} ${EN_CFLAGS_LINK}"
CFLAGS="${EN_CFLAGS_COMMON} ${EN_CFLAGS_COMPILER} ${EN_CFLAGS_CPU} ${EN_CFLAGS_DEBUG} ${EN_CFLAGS_HARDENED} ${EN_CFLAGS_LINK}"
CXXFLAGS="${CFLAGS}"
FCFLAGS="${CFLAGS}"
FFLAGS="${CFLAGS}"
