# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consider using a local mirror.

[arm_armv6j_hf]
priority = 1
sync-uri = http://10.0.2.2:8080/releases/arm/binpackages/23.0/armv6j/hf

[arm_armv6j_sf]
priority = 1
sync-uri = http://10.0.2.2:8080/releases/arm/binpackages/23.0/armv6j/sf

[rv64_lp64d]
priority = 1
sync-uri = http://10.0.2.2:8080/releases/riscv/binpackages/23.0/rv64_lp64d
