[DEFAULT]
main-repo = gentoo

[gentoo]
location = /var/db/repos/gentoo
sync-type = webrsync
#sync-uri = rsync://ftp.belnet.be/gentoo/gentoo/
sync-uri = rsync://mirror.yandex.ru/gentoo-portage/
auto-sync = no
